# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_count_kmers
#' @name rcpp_count_kmers
#' @description returns count kmers
#' @return list
#' @param aavector StringVector [mandatory]
#' @param k kmer length [default: 6]
#' @param ncores number of cores [default: 1]
#' @param aa2int convert aa to Int64 [default: FALSE]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' h <- hiv |> MSA2dist::cds2aa() |> as.character()
#' l <- korthoR::rcpp_count_kmers(
#'     aavector=h,
#'     k=6,
#'     ncores=1)
#' l
#' # to convert aa to Int64
#' lint64 <- korthoR::rcpp_count_kmers(
#'     aavector=h,
#'     k=6,
#'     ncores=1,
#'     aa2int=TRUE)
#' lint64
#' @export rcpp_count_kmers
#' @author Kristian K Ullrich
NULL

rcpp_count_kmers <- function(aavector, k = 6L, ncores = 1L, aa2int = FALSE) {
    .Call(`_korthoR_rcpp_count_kmers`, aavector, k, ncores, aa2int)
}

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_count_mers
#' @name rcpp_count_mers
#' @description returns count all mers
#' @return list
#' @param aavector StringVector [mandatory]
#' @param ncores number of cores [default: 1]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' h <- hiv |> MSA2dist::cds2aa() |> as.character()
#' l <- korthoR::rcpp_count_mers(
#'     aavector=h,
#'     ncores=1)
#' l
#' @export rcpp_count_mers
#' @author Kristian K Ullrich
NULL

rcpp_count_mers <- function(aavector, ncores = 1L) {
    .Call(`_korthoR_rcpp_count_mers`, aavector, ncores)
}

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_jaccard_a_b
#' @name rcpp_jaccard_a_b
#' @description returns jaccard
#' @return list
#' @param kmer_counts_q list [mandatory]
#' @param kmer_counts_t list [mandatory]
#' @param k kmer length [default: 6]
#' @param min_jaccard min jaccard distance to report [default: 0.01]
#' @param ncores number of cores [default: 1]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' l <- hiv |>
#'     MSA2dist::cds2aa() |>
#'     korthoR::count_kmers(k=6)
#' d <- korthoR::rcpp_jaccard_a_b(
#'     kmer_counts_q=l,
#'     kmer_counts_t=l,
#'     k=6,
#'     min_jaccard=0.01,
#'     ncores=1)
#' d
#' @export rcpp_jaccard_a_b
#' @author Kristian K Ullrich
NULL

rcpp_jaccard_a_b <- function(kmer_counts_q, kmer_counts_t, k = 6L, min_jaccard = 0.01, ncores = 1L) {
    .Call(`_korthoR_rcpp_jaccard_a_b`, kmer_counts_q, kmer_counts_t, k, min_jaccard, ncores)
}

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_jaccard_a_b_Int64
#' @name rcpp_jaccard_a_b_Int64
#' @description returns jaccard
#' @return list
#' @param kmer_counts_q_Int64 list [mandatory]
#' @param kmer_counts_t_Int64 list [mandatory]
#' @param k kmer length [default: 6]
#' @param min_jaccard min jaccard distance to report [default: 0.01]
#' @param ncores number of cores [default: 1]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' lint64 <- hiv |>
#'     MSA2dist::cds2aa() |>
#'     korthoR::count_kmers(
#'         k=6,
#'         aa2int=TRUE)
#' d <- korthoR::rcpp_jaccard_a_b_Int64(
#'     kmer_counts_q_Int64=lint64,
#'     kmer_counts_t_Int64=lint64,
#'     k=6,
#'     min_jaccard=0.01,
#'     ncores=1)
#' d
#' @export rcpp_jaccard_a_b_Int64
#' @author Kristian K Ullrich
NULL

rcpp_jaccard_a_b_Int64 <- function(kmer_counts_q_Int64, kmer_counts_t_Int64, k = 6L, min_jaccard = 0.01, ncores = 1L) {
    .Call(`_korthoR_rcpp_jaccard_a_b_Int64`, kmer_counts_q_Int64, kmer_counts_t_Int64, k, min_jaccard, ncores)
}

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_jaccard_sparse
#' @name rcpp_jaccard_sparse
#' @description returns jaccard
#' @return list
#' @param kmer_counts_q list [mandatory]
#' @param kmer_counts_t list [mandatory]
#' @param k kmer length [default: 6]
#' @param min_jaccard min jaccard distance to report [default: 0.01]
#' @param sparse_threshold use sparse_n number subset to evaluate change search strategy [default: 0.1]
#' @param sparse_n number of subset to get sparse threshold [default: 100]
#' @param ncores number of cores [default: 1]
#' @param debug print to console [default: FALSE]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' l <- hiv |>
#'     MSA2dist::cds2aa() |>
#'     korthoR::count_kmers(k=6)
#' d <- korthoR::rcpp_jaccard_sparse(
#'     kmer_counts_q=l,
#'     kmer_counts_t=l,
#'     k=6,
#'     min_jaccard=0.01,
#'     sparse_threshold=0.1,
#'     sparse_n=100,
#'     ncores=1,
#'     debug=FALSE)
#' d
#' @export rcpp_jaccard_sparse
#' @author Kristian K Ullrich
NULL

rcpp_jaccard_sparse <- function(kmer_counts_q, kmer_counts_t, k = 6L, min_jaccard = 0.01, sparse_threshold = 0.1, sparse_n = 100L, ncores = 1L, debug = FALSE) {
    .Call(`_korthoR_rcpp_jaccard_sparse`, kmer_counts_q, kmer_counts_t, k, min_jaccard, sparse_threshold, sparse_n, ncores, debug)
}

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_jaccard_sparse_Int64
#' @name rcpp_jaccard_sparse_Int64
#' @description returns jaccard
#' @return list
#' @param kmer_counts_q_Int64 list [mandatory]
#' @param kmer_counts_t_Int64 list [mandatory]
#' @param k kmer length [default: 6]
#' @param min_jaccard min jaccard distance to report [default: 0.01]
#' @param ncores number of cores [default: 1]
#' @param debug print to console [default: FALSE]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' l <- hiv |>
#'     MSA2dist::cds2aa() |>
#'     korthoR::count_kmers(
#'         k=6,
#'         aa2int=TRUE)
#' d <- korthoR::rcpp_jaccard_sparse_Int64(
#'     kmer_counts_q=l,
#'     kmer_counts_t=l,
#'     k=6,
#'     min_jaccard=0.01,
#'     ncores=1,
#'     debug=FALSE)
#' d
#' @export rcpp_jaccard_sparse_Int64
#' @author Kristian K Ullrich
NULL

rcpp_jaccard_sparse_Int64 <- function(kmer_counts_q_Int64, kmer_counts_t_Int64, k = 6L, min_jaccard = 0.01, ncores = 1L, debug = FALSE) {
    .Call(`_korthoR_rcpp_jaccard_sparse_Int64`, kmer_counts_q_Int64, kmer_counts_t_Int64, k, min_jaccard, ncores, debug)
}

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_jaccard_sparse_a_b
#' @name rcpp_jaccard_sparse_a_b
#' @description returns jaccard
#' @return list
#' @param kmer_counts_q list [mandatory]
#' @param kmer_counts_t list [mandatory]
#' @param k kmer length [default: 6]
#' @param min_jaccard min jaccard distance to report [default: 0.01]
#' @param ncores number of cores [default: 1]
#' @param debug print to console [default: FALSE]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' l <- hiv |>
#'     MSA2dist::cds2aa() |>
#'     korthoR::count_kmers(k=6)
#' d <- korthoR::rcpp_jaccard_sparse_a_b(
#'     kmer_counts_q=l,
#'     kmer_counts_t=l,
#'     k=6,
#'     min_jaccard=0.01,
#'     ncores=1,
#'     debug=FALSE)
#' d
#' @export rcpp_jaccard_sparse_a_b
#' @author Kristian K Ullrich
NULL

rcpp_jaccard_sparse_a_b <- function(kmer_counts_q, kmer_counts_t, k = 6L, min_jaccard = 0.01, ncores = 1L, debug = FALSE) {
    .Call(`_korthoR_rcpp_jaccard_sparse_a_b`, kmer_counts_q, kmer_counts_t, k, min_jaccard, ncores, debug)
}

#' @useDynLib korthoR, .registration = TRUE
#' @import Rcpp
#' @title rcpp_jaccard_sparse_a_b_Int64
#' @name rcpp_jaccard_sparse_a_b_Int64
#' @description returns jaccard
#' @return list
#' @param kmer_counts_q_Int64 list [mandatory]
#' @param kmer_counts_t_Int64_Int64 list [mandatory]
#' @param k kmer length [default: 6]
#' @param min_jaccard min jaccard distance to report [default: 0.01]
#' @param ncores number of cores [default: 1]
#' @param debug print to console [default: FALSE]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' lint64 <- hiv |>
#'     MSA2dist::cds2aa() |>
#'     korthoR::count_kmers(
#'         k=6,
#'         aa2int=TRUE)
#' d <- korthoR::rcpp_jaccard_sparse_a_b_Int64(
#'     kmer_counts_q_Int64=lint64,
#'     kmer_counts_t_Int64=lint64,
#'     k=6,
#'     min_jaccard=0.01,
#'     ncores=1,
#'     debug=FALSE)
#' d
#' @export rcpp_jaccard_sparse_a_b_Int64
#' @author Kristian K Ullrich
NULL

rcpp_jaccard_sparse_a_b_Int64 <- function(kmer_counts_q_Int64, kmer_counts_t_Int64, k = 6L, min_jaccard = 0.01, ncores = 1L, debug = FALSE) {
    .Call(`_korthoR_rcpp_jaccard_sparse_a_b_Int64`, kmer_counts_q_Int64, kmer_counts_t_Int64, k, min_jaccard, ncores, debug)
}

